modLoader="javafml"
loaderVersion="[36,)"
license="GPLv3"
[[mods]]
modId="nosmithing"
version="${file.jarVersion}"
displayName="No Smithing"
displayURL="http://www.curseforge.com/minecraft/mc-mods/no-smithing"
authors="IchHabeHunger54"
description='''
Disables the smithing table functionality.
'''
[[dependencies.nosmithing]]
modId="forge"
versionRange="[36,)"
mandatory=true
ordering="NONE"
side="BOTH"
[[dependencies.nosmithing]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"
